Models/TransferViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ABCMoneyTransfer.Models
{
    public class TransferViewModel
    {
        // Sender Information
        [Required]
        [Display(Name = "First Name")]
        public string SenderFirstName { get; set; }

        [Display(Name = "Middle Name")]
        public string? SenderMiddleName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string SenderLastName { get; set; }

        [Required]
        [Display(Name = "Address")]
        public string SenderAddress { get; set; }

        [Required]
        [Display(Name = "Country")]
        public string SenderCountry { get; set; }

        // Receiver Information
        [Required]
        [Display(Name = "First Name")]
        public string ReceiverFirstName { get; set; }

        [Display(Name = "Middle Name")]
        public string? ReceiverMiddleName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string ReceiverLastName { get; set; }

        [Required]
        [Display(Name = "Address")]
        public string ReceiverAddress { get; set; }

        [Required]
        [Display(Name = "Country")]
        public string ReceiverCountry { get; set; }

        // Payment Details
        [Required]
        [Display(Name = "Bank Name")]
        public string BankName { get; set; }

        [Required]
        [Display(Name = "Account Number")]
        public string AccountNumber { get; set; }

        [Required]
        [Display(Name = "Transfer Amount (MYR)")]
        [DataType(DataType.Currency)]
        [Range(0.01, double.MaxValue, ErrorMessage = "Amount must be greater than 0")]
        public decimal TransferAmount { get; set; }

        [Display(Name = "Exchange Rate (MYR to NPR)")]
        [DataType(DataType.Currency)]
        public decimal ExchangeRate { get; set; }

        [Display(Name = "Payout Amount (NPR)")]
        [DataType(DataType.Currency)]
        public decimal PayoutAmount { get; set; }
    }
}

Controllers/TransferController.cs
using ABCMoneyTransfer.Data;
using ABCMoneyTransfer.Models;
using ABCMoneyTransfer.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Security.Claims;

namespace ABCMoneyTransfer.Controllers
{
    [Authorize]
    public class TransferController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ExchangeRateService _exchangeRateService;
        private readonly BankService _bankService;
        public TransferController(ApplicationDbContext context, ExchangeRateService exchangeRateService, BankService bankService)
        {
            _context = context;
            _exchangeRateService = exchangeRateService;
            _bankService = bankService;
        }

        public async Task<IActionResult> Index()
        {
            var transferViewModel = new TransferViewModel
            {
                SenderFirstName = User.FindFirst("FirstName")?.Value,
                SenderMiddleName = User.FindFirst("MiddleName")?.Value,
                SenderLastName = User.FindFirst("LastName")?.Value,
                SenderAddress = User.FindFirst("Address")?.Value,
                SenderCountry = User.FindFirst("Country")?.Value,
            };

            var banks = await _bankService.GetBanksOfNepal();
            ViewBag.Banks = banks ?? new List<Bank>();

            return View(transferViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> TransferMoney(TransferViewModel model)
        {
            if (ModelState.IsValid) 
            {
                var exchangeRate = await _exchangeRateService.GetExchangeRateOfCountry(DateTime.Now, "MYR");
                model.ExchangeRate = exchangeRate;
                model.PayoutAmount = model.TransferAmount * exchangeRate;

                var sender = new Person
                {
                    FirstName = model.SenderFirstName,
                    MiddleName = model.SenderMiddleName,
                    LastName = model.SenderLastName,
                    Address = model.SenderAddress,
                    Country = model.SenderCountry
                };

                var receiver = new Person
                {
                    FirstName = model.ReceiverFirstName,
                    MiddleName = model.ReceiverMiddleName,
                    LastName = model.ReceiverLastName,
                    Address = model.ReceiverAddress,
                    Country = model.ReceiverCountry
                };

                var transaction = new Transaction
                {
                    Sender = sender,
                    Receiver = receiver,
                    BankName = model.BankName,
                    AccountNumber = model.AccountNumber,
                    TransferAmount = model.TransferAmount,
                    ExchangeRate = model.ExchangeRate,
                    PayoutAmount = model.PayoutAmount,
                    TransactionDate = DateTime.Now
                };

                _context.Transactions.Add(transaction);
                await _context.SaveChangesAsync();


                TempData["TransferDetails"] = JsonConvert.SerializeObject(new TransferSuccessViewModel
                {
                    TransferAmount = model.TransferAmount,
                    ReceiverName = model.ReceiverFirstName,
                    PayoutAmount = model.PayoutAmount
                });

                return RedirectToAction("Index", "Home");
            }
            var banks = await _bankService.GetBanksOfNepal();
            ViewBag.BanksList = banks ?? new List<Bank>();
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> GetExchangeRate()
        {
            var exchangeRate = await _exchangeRateService.GetExchangeRateOfCountry(DateTime.Now, "MYR");
            return Json(new { exchangeRate });
        }
    }
}

Views/Transfer/Create.cshtml
@model TransferViewModel
<h2>Create Transfer</h2>
<form asp-action="Create" method="post" class="row g-2 card">
    <div class="col-md-12">
        <div class="row">
            <h3>Sender Information</h3>
            <div class="col-md-4">
                <label asp-for="SenderFirstName"></label>
                <input asp-for="SenderFirstName" placeholder="first name" class="form-control" />
                <span asp-validation-for="SenderFirstName" class="text-danger"></span>
            </div>
            <div class="col-md-4">
                <label asp-for="SenderMiddleName"></label>
                <input asp-for="SenderMiddleName" placeholder="middle name" class="form-control" />
            </div>
            <div class="col-md-4">
                <label asp-for="SenderLastName"></label>
                <input asp-for="SenderLastName" placeholder="last name" class="form-control" />
                <span asp-validation-for="SenderLastName" class="text-danger"></span>
            </div>
            <div class="col-md-12">
                <label asp-for="SenderAddress"></label>
                <input asp-for="SenderAddress" placeholder="address" class="form-control" />
                <span asp-validation-for="SenderAddress" class="text-danger"></span>
            </div>
            <div class="col-md-12">
                <label asp-for="SenderCountry"></label>
                <input asp-for="SenderCountry" placeholder="country" class="form-control" />
                <span asp-validation-for="SenderCountry" class="text-danger"></span>
            </div>
        </div>
    </div>
   
    <hr />
    <div class="col-md-12">
        <div class="row">
            <h3>Receiver Information</h3>
            <div class="col-md-4">
                <label asp-for="ReceiverFirstName"></label>
                <input asp-for="ReceiverFirstName" placeholder="first name" class="form-control"/>
                <span asp-validation-for="ReceiverFirstName" class="text-danger"></span>
            </div>
            <div class="col-md-4">
                <label asp-for="ReceiverMiddleName"></label>
                <input asp-for="ReceiverMiddleName" placeholder="middle name" class="form-control" />
            </div>
            <div class="col-md-4">
                <label asp-for="ReceiverLastName"></label>
                <input asp-for="ReceiverLastName" placeholder="last name" class="form-control" />
                <span asp-validation-for="ReceiverLastName" class="text-danger"></span>
            </div>
            <div class="col-md-12">
                <label asp-for="ReceiverAddress"></label>
                <input asp-for="ReceiverAddress" placeholder="address" class="form-control" />
                <span asp-validation-for="ReceiverAddress" class="text-danger"></span>
            </div>
            <div class="col-md-12">
                <label asp-for="ReceiverCountry"></label>
                <input asp-for="ReceiverCountry" placeholder="country" class="form-control" />
                <span asp-validation-for="ReceiverCountry" class="text-danger"></span>
            </div>
        </div>
    </div>
   
    <hr />
    <div class="col-md-12">
        <div class="row">
            <h3>Payment Details</h3>
            <div class="col-md-12">
                <label asp-for="BankName"></label>
                <input asp-for="BankName" placeholder="bank name" class="form-control" />
                <span asp-validation-for="BankName" class="text-danger"></span>
            </div>
            <div class="col-md-12">
                <label asp-for="AccountNumber"></label>
                <input asp-for="AccountNumber" placeholder="account number" class="form-control" />
                <span asp-validation-for="AccountNumber" class="text-danger"></span>
            </div>
            <div class="col-md-12">
                <label asp-for="TransferAmount"></label>
                <input asp-for="TransferAmount" id="transferAmount" placeholder="Amount" class="form-control" />
                <span asp-validation-for="TransferAmount" class="text-danger"></span>
            </div>
            <div class="col-md-12">
                <label asp-for="ExchangeRate"></label>
                <input asp-for="ExchangeRate" id="exchangeRate" readonly />
            </div>
            <div class="col-md-12">
                <label asp-for="PayoutAmount"></label>
                <input asp-for="PayoutAmount" id="payoutAmount" readonly />
            </div>
        </div>
    </div>
    
    <div class="col-md-4 my-2">
        <button class="btn btn-success" type="submit">Transfer</button>
    </div>
   
</form>

@section Scripts {
    <script>
        $(document).ready(function () {
            function updateExchangeRate() {
                $.get('@Url.Action("GetExchangeRate", "Transfer")', function (data) {
                    $('#exchangeRate').val(data.exchangeRate.toFixed(4));
                    updatePayoutAmount();
                });
            }

            function updatePayoutAmount() {
                var transferAmount = parseFloat($('#transferAmount').val()) || 0;
                var exchangeRate = parseFloat($('#exchangeRate').val()) || 0;
                var payoutAmount = transferAmount * exchangeRate;
                $('#payoutAmount').val(payoutAmount.toFixed(2));
            }

            updateExchangeRate();
            setInterval(updateExchangeRate, 60000); // Update every minute

            $('#transferAmount').on('input', updatePayoutAmount);
        });
    </script>
}

Views/Transfer/Index.cshtml
@model TransferViewModel

@* @{
    var banks = ViewBag.Banks as List<Bank>;
} *@

<style>
    .select2-container {
        width: 100% !important;
    }
</style>

<h2 class="my-4">Transfer Money</h2>
<form asp-action="TransferMoney" method="post" class="row g-2 card p-4">
    <div class="col-md-12">
        <div class="row g-3">
            <h3>Sender Information</h3>
            <div class="col-md-4">
                <label asp-for="SenderFirstName"></label>
                <input asp-for="SenderFirstName" placeholder="first name" class="form-control" value="@Model.SenderFirstName"  />
                <span asp-validation-for="SenderFirstName" class="text-danger"></span>
            </div>
            <div class="col-md-4">
                <label asp-for="SenderMiddleName"></label>
                <input asp-for="SenderMiddleName" placeholder="middle name" class="form-control" value="@Model.SenderMiddleName"  />
            </div>
            <div class="col-md-4">
                <label asp-for="SenderLastName"></label>
                <input asp-for="SenderLastName" placeholder="last name" class="form-control" value="@Model.SenderLastName"  />
                <span asp-validation-for="SenderLastName" class="text-danger"></span>
            </div>
            <div class="col-md-12">
                <label asp-for="SenderAddress"></label>
                <input asp-for="SenderAddress" placeholder="address" class="form-control" value="@Model.SenderAddress" />
                <span asp-validation-for="SenderAddress" class="text-danger"></span>
            </div>
            <div class="col-md-12">
                <label asp-for="SenderCountry"></label>
                <input asp-for="SenderCountry" placeholder="country" class="form-control" value="@Model.SenderCountry" />
                <span asp-validation-for="SenderCountry" class="text-danger"></span>
            </div>
        </div>
    </div>

    <hr class="my-4" />
    <div class="col-md-12">
        <div class="row g-3">
            <h3>Receiver Information</h3>
            <div class="col-md-4">
                <label asp-for="ReceiverFirstName"></label>
                <input asp-for="ReceiverFirstName" placeholder="first name" class="form-control" />
                <span asp-validation-for="ReceiverFirstName" class="text-danger"></span>
            </div>
            <div class="col-md-4">
                <label asp-for="ReceiverMiddleName"></label>
                <input asp-for="ReceiverMiddleName" placeholder="middle name" class="form-control" />
            </div>
            <div class="col-md-4">
                <label asp-for="ReceiverLastName"></label>
                <input asp-for="ReceiverLastName" placeholder="last name" class="form-control" />
                <span asp-validation-for="ReceiverLastName" class="text-danger"></span>
            </div>
            <div class="col-md-12">
                <label asp-for="ReceiverAddress"></label>
                <input asp-for="ReceiverAddress" placeholder="address" class="form-control" />
                <span asp-validation-for="ReceiverAddress" class="text-danger"></span>
            </div>
            <div class="col-md-12">
                <label asp-for="ReceiverCountry"></label>
                <input asp-for="ReceiverCountry" placeholder="country" class="form-control" />
                <span asp-validation-for="ReceiverCountry" class="text-danger"></span>
            </div>
        </div>
    </div>

    <hr class="my-4" />
    <div class="col-md-12">
        <div class="row g-3">
            <h3>Payment Details</h3>
            @if (ViewBag.Banks is List<Bank> banks && banks.Count > 0)
            {
                <div class="col-md-12">
                    <label asp-for="BankName"></label>
                    <select asp-for="BankName" id="banksDropdown" name="BankName" class="form-select">
                        <option value="">Select a Bank</option>
                        @foreach (var bank in banks)
                        {
                            <option value="@bank.Code">@bank.Title</option>
                        }
                    </select>
                    <span asp-validation-for="BankName" class="text-danger"></span>
                </div>
            }
            else
            {
                <div class="col-md-12">
                    <label asp-for="BankName"></label>
                    <input asp-for="BankName" placeholder="Please select Recipient bank name" class="form-control" />
                    <span asp-validation-for="BankName" class="text-danger"></span>
                </div>
                
            }

            <div class="col-md-12">
                <label asp-for="AccountNumber"></label>
                <input asp-for="AccountNumber" placeholder="account number" class="form-control" />
                <span asp-validation-for="AccountNumber" class="text-danger"></span>
            </div>
            <div class="col-md-12">
                <label asp-for="TransferAmount"></label>
                <input asp-for="TransferAmount" id="transferAmount" placeholder="Amount" class="form-control" />
                <span asp-validation-for="TransferAmount" class="text-danger"></span>
            </div>
            <div class="col-md-12">
                <label asp-for="ExchangeRate"></label>
                <input asp-for="ExchangeRate" id="exchangeRate" readonly class="form-control" />
            </div>
            <div class="col-md-12">
                <label asp-for="PayoutAmount"></label>
                <input asp-for="PayoutAmount" id="payoutAmount" readonly class="form-control" />
            </div>
        </div>
    </div>

    <div class="col-md-4 my-2">
        <button class="btn btn-success" type="submit">Transfer</button>
    </div>

</form>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#banksDropdown').select2({
                placeholder: "Please select recipient's bank name",
                allowClear: true,
                width: "100%"
            });
            function updateExchangeRate() {
                $.get('@Url.Action("GetExchangeRate", "Transfer")', function (data) {
                    $('#exchangeRate').val(data.exchangeRate.toFixed(4));
                    updatePayoutAmount();
                });
            }

            function updatePayoutAmount() {
                var transferAmount = parseFloat($('#transferAmount').val()) || 0;
                var exchangeRate = parseFloat($('#exchangeRate').val()) || 0;
                var payoutAmount = transferAmount * exchangeRate;
                $('#payoutAmount').val(payoutAmount.toFixed(2));
            }

            updateExchangeRate();
            setInterval(updateExchangeRate, 60000); // Update every minute

            $('#transferAmount').on('input', updatePayoutAmount);
        });
    </script>
}

Views/Transfer/TransferMoney.cshtml
@model TransferViewModel

@* @{
   var banks = ViewBag.Banks as List<Bank>;
} *@

<style>
    .select2-container {
        width: 100% !important;
    }
</style>

<h2 class="my-4">Transfer Money</h2>
<form asp-action="TransferMoney" method="post" class="row g-2 card p-4" >
    <div class="col-md-12">
        <div class="row g-3">
            <h3>Sender Information</h3>
            <div class="col-md-4">
                <label asp-for="SenderFirstName"></label>
                <input asp-for="SenderFirstName" placeholder="first name" class="form-control" value="@Model.SenderFirstName" />
                <span asp-validation-for="SenderFirstName" class="text-danger"></span>
            </div>
            <div class="col-md-4">
                <label asp-for="SenderMiddleName"></label>
                <input asp-for="SenderMiddleName" placeholder="middle name" class="form-control" value="@Model.SenderMiddleName" />
            </div>
            <div class="col-md-4">
                <label asp-for="SenderLastName"></label>
                <input asp-for="SenderLastName" placeholder="last name" class="form-control" value="@Model.SenderLastName" />
                <span asp-validation-for="SenderLastName" class="text-danger"></span>
            </div>
            <div class="col-md-12">
                <label asp-for="SenderAddress"></label>
                <input asp-for="SenderAddress" placeholder="address" class="form-control" value="@Model.SenderAddress" />
                <span asp-validation-for="SenderAddress" class="text-danger"></span>
            </div>
            <div class="col-md-12">
                <label asp-for="SenderCountry"></label>
                <input asp-for="SenderCountry" placeholder="country" class="form-control" value="@Model.SenderCountry" />
                <span asp-validation-for="SenderCountry" class="text-danger"></span>
            </div>
        </div>
    </div>

    <hr class="my-4" />
    <div class="col-md-12">
        <div class="row g-3">
            <h3>Receiver Information</h3>
            <div class="col-md-4">
                <label asp-for="ReceiverFirstName"></label>
                <input asp-for="ReceiverFirstName" placeholder="first name" class="form-control" />
                <span asp-validation-for="ReceiverFirstName" class="text-danger"></span>
            </div>
            <div class="col-md-4">
                <label asp-for="ReceiverMiddleName"></label>
                <input asp-for="ReceiverMiddleName" placeholder="middle name" class="form-control" />
            </div>
            <div class="col-md-4">
                <label asp-for="ReceiverLastName"></label>
                <input asp-for="ReceiverLastName" placeholder="last name" class="form-control" />
                <span asp-validation-for="ReceiverLastName" class="text-danger"></span>
            </div>
            <div class="col-md-12">
                <label asp-for="ReceiverAddress"></label>
                <input asp-for="ReceiverAddress" placeholder="address" class="form-control" />
                <span asp-validation-for="ReceiverAddress" class="text-danger"></span>
            </div>
            <div class="col-md-12">
                <label asp-for="ReceiverCountry"></label>
                <input asp-for="ReceiverCountry" placeholder="country" class="form-control" />
                <span asp-validation-for="ReceiverCountry" class="text-danger"></span>
            </div>
        </div>
    </div>

    <hr class="my-4" />
    <div class="col-md-12">
        <div class="row g-3">
            <h3>Payment Details</h3>
            @if (ViewBag.BanksList is List<Bank> banks && banks.Count > 0)
            {
                <div class="col-md-12">
                    <label asp-for="BankName"></label>
                    <select asp-for="BankName" id="banksDropdown" name="BankName" class="form-select">
                        <option value="">Select a Bank</option>
                        @foreach (var bank in banks)
                        {
                            <option value="@bank.Code">@bank.Title</option>
                        }
                    </select>
                    <span asp-validation-for="BankName" class="text-danger"></span>
                </div>
               
            }
            else
            {
                <div class="col-md-12">
                    <label asp-for="BankName"></label>
                    <input asp-for="BankName" placeholder="Please select Recipient bank name" class="form-control" />
                    <span asp-validation-for="BankName" class="text-danger"></span>
                </div>
            }

            <div class="col-md-12">
                <label asp-for="AccountNumber"></label>
                <input asp-for="AccountNumber" placeholder="account number" class="form-control" />
                <span asp-validation-for="AccountNumber" class="text-danger"></span>
            </div>
            <div class="col-md-12">
                <label asp-for="TransferAmount"></label>
                <input asp-for="TransferAmount" id="transferAmount" placeholder="Amount" class="form-control" />
                <span asp-validation-for="TransferAmount" class="text-danger"></span>
            </div>
            <div class="col-md-12">
                <label asp-for="ExchangeRate"></label>
                <input asp-for="ExchangeRate" id="exchangeRate" readonly class="form-control" />
            </div>
            <div class="col-md-12">
                <label asp-for="PayoutAmount"></label>
                <input asp-for="PayoutAmount" id="payoutAmount" readonly class="form-control" />
            </div>
        </div>
    </div>

    <div class="col-md-4 my-2">
        <button class="btn btn-success" type="submit">Transfer</button>
    </div>

</form>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#banksDropdown').select2({
                placeholder: "Please select recipient's bank name",
                allowClear: true,
                width: "100%"
            });
            function updateExchangeRate() {
                $.get('@Url.Action("GetExchangeRate", "Transfer")', function (data) {
                    $('#exchangeRate').val(data.exchangeRate.toFixed(4));
                    updatePayoutAmount();
                });
            }

            function updatePayoutAmount() {
                var transferAmount = parseFloat($('#transferAmount').val()) || 0;
                var exchangeRate = parseFloat($('#exchangeRate').val()) || 0;
                var payoutAmount = transferAmount * exchangeRate;
                $('#payoutAmount').val(payoutAmount.toFixed(2));
            }

            updateExchangeRate();
            setInterval(updateExchangeRate, 60000); // Update every minute

            $('#transferAmount').on('input', updatePayoutAmount);
        });
    </script>
}